### ISSUE TITLE
After installing Greenlight with bbb-install.sh no SSL certificate (site not secure)

### ISSUE THREAD

**Issue by ricubuntu** [bigbluebutton/greenlight#1006]
Hello!
I installed BBB adn Greenlight.
The default command didn't work but i fixed with this suggestion (changing the address in the command):
https://github.com/bigbluebutton/bbb-install/issues/120

Now greenlight is working but I still don't have the SSL Certificate.
Can you help?
Thank you!
Riccardo

**Comment by farhatahmad** [comment]
Hi @ricubuntu,

I believe your issue was solved in the forum. Please don't double post next time

**Comment by ricubuntu** [comment]
Hello,
the problem is not solved yet.
I'm still waiting for support. Https://meet.pharmagrin.net si secure but
when any user type meet.pharmagrin.net it lands on
HTTP://meet.pharmagrin.net.
How can I make it to land on https instead of http?
Please help
Thank you
Riccardo

Il giorno mar 17 mar 2020 alle ore 19:14 Ahmad Farhat <
notifications@github.com> ha scritto:

**Comment by farhatahmad** [comment]
@ricubuntu 

I found this website by doing a quick google 

https://serversforhackers.com/c/redirect-http-to-https-nginx

**Comment by ricubuntu** [comment]
Thank you I read the article.
I'm not an expert so I can edit as suggested but I need to know what file to edit. It's not explicited in the guide.
Can you help?
R

**Comment by geomatica4** [comment]
Instalo bbb mediante el comando wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-22 -g toda la instalación termina correctamente pero al llamar el servicio por el navegador me responde "conexión rechazada", deshabilité el cortafuego, verifiqué que todos los servicios estuvieran corriendo y escuchando por los puertos correctos.
Alguna idea?
